### PR TITLE
Changed some values (URL Scheme & Square App ID) for clarity

### PR DESCRIPTION
**Pull request by sidsharma27**

### CODE REVIEW

**Comment by gizmosachin** [comment]
Hi @sidsharma27, thanks for the pull request! Those values are intentionally formatted that way in the README so that they produce placeholders when copied and pasted into Xcode.

**Comment by jawspeak** [comment]
The suggestion though is to have `://` at the end. The intention of non-compilable code is for people to put their own value in, however they also need to know to have `://`. 

How about we use this: `<#T##Your URL Scheme##String#> replaceme://` or `<#T##Your URL Scheme##String# --> "replaceme://"` or `<#T##Your URL Scheme##String#>://` or some other variation?

**Comment by gizmosachin** [comment]
Ah, I totally missed the double slash at the end - apologies @sidsharma27, that's much clearer. 

Thoughts on `"<#T##Your URL Scheme##String#>://"` for the Swift sample and `@"<#T##Your URL Scheme##NSString#>://"` for the Objective-C one? That way when pasted into Xcode "Your URL Scheme" becomes a placeholder but the `://` stays after you click it and start typing.

**Comment by gizmosachin** [comment]
Since this PR didn't update the Obj-C sample, I manually made the equivalent change on master, so closing this. Link to change: https://github.com/square/SquarePointOfSaleSDK-iOS/commit/fa969da182b89ae0ca151d2260fe2c420347c8e2

**Pull request closed without merging**
